# Generated by Django 5.1.1 on 2026-01-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_feedback', models.TextField()),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommended_topics', models.JSONField(blank=True, default=list)),
                ('personalized_message', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDocumentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_modules', models.IntegerField(default=0)),
                ('completed_modules', models.IntegerField(default=0)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('total_time_spent_seconds', models.IntegerField(default=0)),
                ('weak_concepts', models.JSONField(blank=True, default=list)),
                ('strong_concepts', models.JSONField(blank=True, default=list)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_document_stats',
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=50)),
                ('best_score', models.FloatField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('mastery_level', models.FloatField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_module_progress',
            },
        ),
    ]
