# Generated by Django 5.1.1 on 2026-01-19 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('feedback', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreport',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_report', to='quizzes.quizattempt'),
        ),
        migrations.AddField(
            model_name='userdocumentstats',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='documents.document'),
        ),
    ]
