# Generated by Django 5.1.1 on 2026-01-19 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        ('feedback', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentstats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='documents.module'),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['attempt_id'], name='idx_feedback_attempt_id'),
        ),
        migrations.AddIndex(
            model_name='userdocumentstats',
            index=models.Index(fields=['user_id'], name='idx_doc_stats_user_id'),
        ),
        migrations.AlterUniqueTogether(
            name='userdocumentstats',
            unique_together={('user', 'document')},
        ),
        migrations.AddIndex(
            model_name='usermoduleprogress',
            index=models.Index(fields=['user_id'], name='idx_progress_user_id'),
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleprogress',
            unique_together={('user', 'module')},
        ),
    ]
