# Generated by Django 5.1.1 on 2026-01-19 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='documents.document'),
        ),
        migrations.AddField(
            model_name='modulechunk',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.module'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user_id'], name='idx_documents_user_id'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='idx_documents_status'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['document_id'], name='idx_modules_document_id'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['document_id', 'module_order'], name='idx_modules_order'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('document', 'module_order')},
        ),
        migrations.AddIndex(
            model_name='modulechunk',
            index=models.Index(fields=['module_id'], name='idx_chunks_module_id'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['idempotency_key'], name='idx_proc_jobs_idemp'),
        ),
    ]
