# Generated by Django 5.2.10 on 2026-01-19 09:46

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='modulechunk',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], name='idx_chunks_embedding', opclasses=['vector_cosine_ops']),
        ),
    ]
