# Generated by Django 5.1.1 on 2026-01-19 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.quizattempt'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quizzes.question'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['module_id'], name='idx_quizzes_module_id'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz_id'], name='idx_questions_quiz_id'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['concept_covered'], name='idx_questions_concept'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user_id'], name='idx_attempts_user_id'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz_id'], name='idx_attempts_quiz_id'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz', 'attempt_number')},
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['attempt_id'], name='idx_answers_attempt_id'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['question_id'], name='idx_answers_question_id'),
        ),
    ]
